settings:
  jira_project_key: "ISD"
  status_mapping:
    opened: Untriaged
    closed: done
    not_planned: rejected
    
  components:
    - traefik

  add_gh_comment: false
  sync_description: false
  sync_comments: false

  label_mapping:
    "Type: Enhancement": Story
